import type { MetadataRoute } from 'next'
import { siteConfig } from '@/data/siteData'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/v1/',
          '/v2/',
          '/v3/',
          '/api/',
          '/?s=',
          '/cdn-cgi/',
        ],
      },
      { userAgent: 'Googlebot', allow: '/' },
      { userAgent: 'Googlebot/2.1', allow: '/' },
      { userAgent: 'Googlebot-Image', allow: '/' },
      { userAgent: 'Googlebot-News', allow: '/' },
      { userAgent: 'Googlebot-Video', allow: '/' },
      { userAgent: 'Google-Extended', allow: '/' },
      { userAgent: 'Gemini-User', allow: '/' },
      { userAgent: 'bingbot', allow: '/' },
      { userAgent: 'Bingbot/2.0', allow: '/' },
      { userAgent: 'GPTBot', allow: '/' },
      { userAgent: 'GPTBot/1.1', allow: '/' },
      { userAgent: 'GPTBot/1.2', allow: '/' },
      { userAgent: 'ChatGPT-User', allow: '/' },
      { userAgent: 'OAI-SearchBot', allow: '/' },
      { userAgent: 'ClaudeBot', allow: '/' },
      { userAgent: 'Claude-Web', allow: '/' },
      { userAgent: 'Claude-User', allow: '/' },
      { userAgent: 'Claude-SearchBot', allow: '/' },
      { userAgent: 'anthropic-ai', allow: '/' },
      { userAgent: 'PerplexityBot', allow: '/' },
      { userAgent: 'Perplexity-User', allow: '/' },
      { userAgent: 'Applebot', allow: '/' },
      { userAgent: 'Applebot-Extended', allow: '/' },
      { userAgent: 'Meta-ExternalAgent', allow: '/' },
      { userAgent: 'Meta-ExternalFetcher', allow: '/' },
      { userAgent: 'FacebookBot', allow: '/' },
      { userAgent: 'Amazonbot', allow: '/' },
      { userAgent: 'NovaAct', allow: '/' },
      { userAgent: 'Bytespider', allow: '/' },
      { userAgent: 'DuckAssistBot', allow: '/' },
      { userAgent: 'cohere-ai', allow: '/' },
      { userAgent: 'cohere-training-data-crawler', allow: '/' },
      { userAgent: 'MistralAI-User', allow: '/' },
      { userAgent: 'YouBot', allow: '/' },
      { userAgent: 'CCBot', allow: '/' },
      { userAgent: 'AI2Bot', allow: '/' },
      { userAgent: 'Kangaroo Bot', allow: '/' },
      { userAgent: 'PodcastBot', allow: '/' },
      { userAgent: 'iTMS', allow: '/' },
      { userAgent: 'Spotify', allow: '/' },
      { userAgent: 'SpotifyBot', allow: '/' },
    ],
    sitemap: `${siteConfig.podcastUrl}/sitemap.xml`,
  }
}
